// Historical NFL Picks Data - Weeks 1-15 (2024 Season)
// Auto-generated from Google Sheets data

const HISTORICAL_GAMES = {
    1: [
        { id: 1, away: 'Cowboys', home: 'Eagles', spread: 8.5, favorite: 'home' },
        { id: 2, away: 'Chiefs', home: 'Chargers', spread: 3, favorite: 'away' },
        { id: 3, away: 'Cardinals', home: 'Saints', spread: 6.5, favorite: 'away' },
        { id: 4, away: 'Panthers', home: 'Jaguars', spread: 3.5, favorite: 'home' },
        { id: 5, away: 'Bengals', home: 'Browns', spread: 5.5, favorite: 'away' },
        { id: 6, away: 'Raiders', home: 'Patriots', spread: 2.5, favorite: 'home' },
        { id: 7, away: 'Dolphins', home: 'Colts', spread: 1.5, favorite: 'home' },
        { id: 8, away: 'Giants', home: 'Commanders', spread: 6.5, favorite: 'home' },
        { id: 9, away: 'Steelers', home: 'Jets', spread: 3, favorite: 'away' },
        { id: 10, away: 'Buccs', home: 'Falcons', spread: 1.5, favorite: 'away' },
        { id: 11, away: '49ers', home: 'Seahawks', spread: 1.5, favorite: 'away' },
        { id: 12, away: 'Titans', home: 'Broncos', spread: 8.5, favorite: 'home' },
        { id: 13, away: 'Lions', home: 'Packers', spread: 2.5, favorite: 'home' },
        { id: 14, away: 'Texans', home: 'Rams', spread: 3, favorite: 'home' },
        { id: 15, away: 'Ravens', home: 'Bills', spread: 1.5, favorite: 'away' },
        { id: 16, away: 'Vikings', home: 'Bears', spread: 1.5, favorite: 'away' }
    ],
    2: [
        { id: 1, away: 'Commanders', home: 'Packers', spread: 3.5, favorite: 'home' },
        { id: 2, away: 'Bills', home: 'Jets', spread: 6.5, favorite: 'away' },
        { id: 3, away: 'Bears', home: 'Lions', spread: 6.5, favorite: 'home' },
        { id: 4, away: 'Browns', home: 'Ravens', spread: 11.5, favorite: 'home' },
        { id: 5, away: 'Jaguars', home: 'Bengals', spread: 3.5, favorite: 'home' },
        { id: 6, away: 'Rams', home: 'Titans', spread: 5.5, favorite: 'away' },
        { id: 7, away: 'Patriots', home: 'Dolphins', spread: 2.5, favorite: 'home' },
        { id: 8, away: 'Giants', home: 'Cowboys', spread: 4.5, favorite: 'home' },
        { id: 9, away: '49ers', home: 'Saints', spread: 3, favorite: 'away' },
        { id: 10, away: 'Seahawks', home: 'Steelers', spread: 3, favorite: 'home' },
        { id: 11, away: 'Panthers', home: 'Cardinals', spread: 6.5, favorite: 'home' },
        { id: 12, away: 'Broncos', home: 'Colts', spread: 2.5, favorite: 'away' },
        { id: 13, away: 'Eagles', home: 'Chiefs', spread: 1.5, favorite: 'away' },
        { id: 14, away: 'Falcons', home: 'Vikings', spread: 3.5, favorite: 'home' },
        { id: 15, away: 'Buccs', home: 'Texans', spread: 2.5, favorite: 'home' },
        { id: 16, away: 'Chargers', home: 'Raiders', spread: 3, favorite: 'away' }
    ],
    3: [
        { id: 1, away: 'Dolphins', home: 'Bills', spread: 11.5, favorite: 'home' },
        { id: 2, away: 'Falcons', home: 'Panthers', spread: 5.5, favorite: 'away' },
        { id: 3, away: 'Bengals', home: 'Vikings', spread: 3, favorite: 'home' },
        { id: 4, away: 'Packers', home: 'Browns', spread: 7.5, favorite: 'away' },
        { id: 5, away: 'Texans', home: 'Jaguars', spread: 1.5, favorite: 'home' },
        { id: 6, away: 'Colts', home: 'Titans', spread: 4.5, favorite: 'away' },
        { id: 7, away: 'Raiders', home: 'Commanders', spread: 3, favorite: 'home' },
        { id: 8, away: 'Rams', home: 'Eagles', spread: 3.5, favorite: 'home' },
        { id: 9, away: 'Jets', home: 'Buccs', spread: 6.5, favorite: 'home' },
        { id: 10, away: 'Steelers', home: 'Patriots', spread: 1.5, favorite: 'away' },
        { id: 11, away: 'Broncos', home: 'Chargers', spread: 3, favorite: 'home' },
        { id: 12, away: 'Saints', home: 'Seahawks', spread: 7.5, favorite: 'home' },
        { id: 13, away: 'Cardinals', home: '49ers', spread: 2.5, favorite: 'home' },
        { id: 14, away: 'Cowboys', home: 'Bears', spread: 1.5, favorite: 'away' },
        { id: 15, away: 'Chiefs', home: 'Giants', spread: 5.5, favorite: 'away' },
        { id: 16, away: 'Lions', home: 'Ravens', spread: 5.5, favorite: 'home' }
    ],
    4: [
        { id: 1, away: 'Seahawks', home: 'Cardinals', spread: 1.5, favorite: 'away' },
        { id: 2, away: 'Vikings', home: 'Steelers', spread: 2.5, favorite: 'away' },
        { id: 3, away: 'Panthers', home: 'Patriots', spread: 5.5, favorite: 'home' },
        { id: 4, away: 'Browns', home: 'Lions', spread: 9.5, favorite: 'home' },
        { id: 5, away: 'Chargers', home: 'Giants', spread: 6.5, favorite: 'away' },
        { id: 6, away: 'Saints', home: 'Bills', spread: 14.5, favorite: 'home' },
        { id: 7, away: 'Eagles', home: 'Buccs', spread: 3.5, favorite: 'away' },
        { id: 8, away: 'Titans', home: 'Texans', spread: 7.5, favorite: 'home' },
        { id: 9, away: 'Commanders', home: 'Falcons', spread: 2.5, favorite: 'home' },
        { id: 10, away: 'Colts', home: 'Rams', spread: 3.5, favorite: 'home' },
        { id: 11, away: 'Jaguars', home: '49ers', spread: 3.5, favorite: 'home' },
        { id: 12, away: 'Ravens', home: 'Chiefs', spread: 2.5, favorite: 'away' },
        { id: 13, away: 'Bears', home: 'Raiders', spread: 1.5, favorite: 'home' },
        { id: 14, away: 'Packers', home: 'Cowboys', spread: 6.5, favorite: 'away' },
        { id: 15, away: 'Jets', home: 'Dolphins', spread: 2.5, favorite: 'home' },
        { id: 16, away: 'Bengals', home: 'Broncos', spread: 7.5, favorite: 'home' }
    ],
    5: [
        { id: 1, away: '49ers', home: 'Rams', spread: 7.5, favorite: 'home' },
        { id: 2, away: 'Vikings', home: 'Browns', spread: 3.5, favorite: 'away' },
        { id: 3, away: 'Cowboys', home: 'Jets', spread: 1.5, favorite: 'away' },
        { id: 4, away: 'Broncos', home: 'Eagles', spread: 4.5, favorite: 'home' },
        { id: 5, away: 'Texans', home: 'Ravens', spread: 1.5, favorite: 'away' },
        { id: 6, away: 'Raiders', home: 'Colts', spread: 7, favorite: 'home' },
        { id: 7, away: 'Dolphins', home: 'Panthers', spread: 1.5, favorite: 'away' },
        { id: 8, away: 'Giants', home: 'Saints', spread: 1.5, favorite: 'home' },
        { id: 9, away: 'Buccs', home: 'Seahawks', spread: 3.5, favorite: 'home' },
        { id: 10, away: 'Titans', home: 'Cardinals', spread: 8.5, favorite: 'home' },
        { id: 11, away: 'Lions', home: 'Bengals', spread: 10.5, favorite: 'away' },
        { id: 12, away: 'Commanders', home: 'Chargers', spread: 2.5, favorite: 'home' },
        { id: 13, away: 'Patriots', home: 'Bills', spread: 8.5, favorite: 'home' },
        { id: 14, away: 'Chiefs', home: 'Jaguars', spread: 3, favorite: 'away' }
    ],
    6: [
        { id: 1, away: 'Eagles', home: 'Giants', spread: 7.5, favorite: 'away' },
        { id: 2, away: 'Broncos', home: 'Jets', spread: 7, favorite: 'away' },
        { id: 3, away: 'Cardinals', home: 'Colts', spread: 9.5, favorite: 'home' },
        { id: 4, away: 'Browns', home: 'Steelers', spread: 5.5, favorite: 'home' },
        { id: 5, away: 'Cowboys', home: 'Panthers', spread: 3, favorite: 'away' },
        { id: 6, away: 'Chargers', home: 'Dolphins', spread: 3.5, favorite: 'away' },
        { id: 7, away: 'Rams', home: 'Ravens', spread: 7, favorite: 'away' },
        { id: 8, away: 'Patriots', home: 'Saints', spread: 3.5, favorite: 'away' },
        { id: 9, away: 'Seahawks', home: 'Jaguars', spread: 1.5, favorite: 'away' },
        { id: 10, away: 'Titans', home: 'Raiders', spread: 4.5, favorite: 'home' },
        { id: 11, away: 'Bengals', home: 'Packers', spread: 14.5, favorite: 'home' },
        { id: 12, away: '49ers', home: 'Buccs', spread: 3.5, favorite: 'home' },
        { id: 13, away: 'Lions', home: 'Chiefs', spread: 2.5, favorite: 'home' },
        { id: 14, away: 'Bills', home: 'Falcons', spread: 4.5, favorite: 'away' },
        { id: 15, away: 'Bears', home: 'Commanders', spread: 4.5, favorite: 'home' }
    ],
    7: [
        { id: 1, away: 'Steelers', home: 'Bengals', spread: 5.5, favorite: 'away' },
        { id: 2, away: 'Rams', home: 'Jaguars', spread: 3, favorite: 'away' },
        { id: 3, away: 'Panthers', home: 'Jets', spread: 1.5, favorite: 'away' },
        { id: 4, away: 'Raiders', home: 'Chiefs', spread: 12.5, favorite: 'home' },
        { id: 5, away: 'Dolphins', home: 'Browns', spread: 2.5, favorite: 'home' },
        { id: 6, away: 'Patriots', home: 'Titans', spread: 6.5, favorite: 'away' },
        { id: 7, away: 'Saints', home: 'Bears', spread: 4.5, favorite: 'home' },
        { id: 8, away: 'Eagles', home: 'Vikings', spread: 2.5, favorite: 'away' },
        { id: 9, away: 'Colts', home: 'Chargers', spread: 1.5, favorite: 'home' },
        { id: 10, away: 'Giants', home: 'Broncos', spread: 7.5, favorite: 'home' },
        { id: 11, away: 'Packers', home: 'Cardinals', spread: 7, favorite: 'away' },
        { id: 12, away: 'Commanders', home: 'Cowboys', spread: 1.5, favorite: 'home' },
        { id: 13, away: 'Falcons', home: '49ers', spread: 1.5, favorite: 'home' },
        { id: 14, away: 'Buccs', home: 'Lions', spread: 5.5, favorite: 'home' },
        { id: 15, away: 'Texans', home: 'Seahawks', spread: 3, favorite: 'home' }
    ],
    8: [
        { id: 1, away: 'Vikings', home: 'Chargers', spread: 3, favorite: 'home' },
        { id: 2, away: 'Bills', home: 'Panthers', spread: 7.5, favorite: 'away' },
        { id: 3, away: 'Bears', home: 'Ravens', spread: 2.5, favorite: 'home' },
        { id: 4, away: 'Browns', home: 'Patriots', spread: 7, favorite: 'home' },
        { id: 5, away: 'Dolphins', home: 'Falcons', spread: 6.5, favorite: 'home' },
        { id: 6, away: 'Giants', home: 'Eagles', spread: 7.5, favorite: 'home' },
        { id: 7, away: 'Jets', home: 'Bengals', spread: 6.5, favorite: 'home' },
        { id: 8, away: '49ers', home: 'Texans', spread: 2.5, favorite: 'home' },
        { id: 9, away: 'Buccs', home: 'Saints', spread: 3.5, favorite: 'away' },
        { id: 10, away: 'Cowboys', home: 'Broncos', spread: 3.5, favorite: 'home' },
        { id: 11, away: 'Titans', home: 'Colts', spread: 14.5, favorite: 'home' },
        { id: 12, away: 'Packers', home: 'Steelers', spread: 3, favorite: 'away' },
        { id: 13, away: 'Commanders', home: 'Chiefs', spread: 11.5, favorite: 'home' }
    ],
    9: [
        { id: 1, away: 'Ravens', home: 'Dolphins', spread: 7.5, favorite: 'away' },
        { id: 2, away: 'Falcons', home: 'Patriots', spread: 4.5, favorite: 'home' },
        { id: 3, away: 'Panthers', home: 'Packers', spread: 13.5, favorite: 'home' },
        { id: 4, away: 'Bears', home: 'Bengals', spread: 2.5, favorite: 'away' },
        { id: 5, away: 'Broncos', home: 'Texans', spread: 1.5, favorite: 'home' },
        { id: 6, away: 'Colts', home: 'Steelers', spread: 3.5, favorite: 'home' },
        { id: 7, away: 'Chargers', home: 'Titans', spread: 9.5, favorite: 'away' },
        { id: 8, away: 'Vikings', home: 'Lions', spread: 8.5, favorite: 'home' },
        { id: 9, away: '49ers', home: 'Giants', spread: 2.5, favorite: 'away' },
        { id: 10, away: 'Jaguars', home: 'Raiders', spread: 2.5, favorite: 'away' },
        { id: 11, away: 'Saints', home: 'Rams', spread: 14.5, favorite: 'home' },
        { id: 12, away: 'Chiefs', home: 'Bills', spread: 1.5, favorite: 'away' },
        { id: 13, away: 'Seahawks', home: 'Commanders', spread: 3, favorite: 'away' },
        { id: 14, away: 'Cardinals', home: 'Cowboys', spread: 3, favorite: 'home' }
    ],
    10: [
        { id: 1, away: 'Raiders', home: 'Broncos', spread: 8.5, favorite: 'home' },
        { id: 2, away: 'Falcons', home: 'Colts', spread: 6.5, favorite: 'home' },
        { id: 3, away: 'Ravens', home: 'Vikings', spread: 4.5, favorite: 'away' },
        { id: 4, away: 'Bills', home: 'Dolphins', spread: 9.5, favorite: 'away' },
        { id: 5, away: 'Browns', home: 'Jets', spread: 2.5, favorite: 'home' },
        { id: 6, away: 'Jaguars', home: 'Texans', spread: 1, favorite: 'away' },
        { id: 7, away: 'Patriots', home: 'Buccs', spread: 2.5, favorite: 'home' },
        { id: 8, away: 'Saints', home: 'Panthers', spread: 5.5, favorite: 'home' },
        { id: 9, away: 'Giants', home: 'Bears', spread: 4.5, favorite: 'home' },
        { id: 10, away: 'Cardinals', home: 'Seahawks', spread: 7, favorite: 'home' },
        { id: 11, away: 'Lions', home: 'Commanders', spread: 7.5, favorite: 'away' },
        { id: 12, away: 'Rams', home: '49ers', spread: 5.5, favorite: 'away' },
        { id: 13, away: 'Steelers', home: 'Chargers', spread: 2.5, favorite: 'home' },
        { id: 14, away: 'Eagles', home: 'Packers', spread: 1.5, favorite: 'home' }
    ],
    11: [
        { id: 1, away: 'Jets', home: 'Patriots', spread: 12.5, favorite: 'home' },
        { id: 2, away: 'Commanders', home: 'Dolphins', spread: 2.5, favorite: 'home' },
        { id: 3, away: 'Panthers', home: 'Falcons', spread: 3.5, favorite: 'home' },
        { id: 4, away: 'Bears', home: 'Vikings', spread: 2.5, favorite: 'home' },
        { id: 5, away: 'Bengals', home: 'Steelers', spread: 5.5, favorite: 'home' },
        { id: 6, away: 'Packers', home: 'Giants', spread: 7.5, favorite: 'away' },
        { id: 7, away: 'Texans', home: 'Titans', spread: 5.5, favorite: 'away' },
        { id: 8, away: 'Chargers', home: 'Jaguars', spread: 3, favorite: 'away' },
        { id: 9, away: 'Buccs', home: 'Bills', spread: 6.5, favorite: 'home' },
        { id: 10, away: '49ers', home: 'Cardinals', spread: 3.5, favorite: 'away' },
        { id: 11, away: 'Seahawks', home: 'Rams', spread: 3, favorite: 'home' },
        { id: 12, away: 'Ravens', home: 'Browns', spread: 7.5, favorite: 'away' },
        { id: 13, away: 'Chiefs', home: 'Broncos', spread: 4.5, favorite: 'away' },
        { id: 14, away: 'Lions', home: 'Eagles', spread: 2.5, favorite: 'home' },
        { id: 15, away: 'Cowboys', home: 'Raiders', spread: 3.5, favorite: 'away' }
    ],
    12: [
        { id: 1, away: 'Bills', home: 'Texans', spread: 5.5, favorite: 'away' },
        { id: 2, away: 'Vikings', home: 'Packers', spread: 6.5, favorite: 'home' },
        { id: 3, away: 'Patriots', home: 'Bengals', spread: 7.5, favorite: 'away' },
        { id: 4, away: 'Giants', home: 'Lions', spread: 13.5, favorite: 'home' },
        { id: 5, away: 'Jets', home: 'Ravens', spread: 13.5, favorite: 'home' },
        { id: 6, away: 'Steelers', home: 'Bears', spread: 3, favorite: 'home' },
        { id: 7, away: 'Seahawks', home: 'Titans', spread: 12.5, favorite: 'away' },
        { id: 8, away: 'Colts', home: 'Chiefs', spread: 3.5, favorite: 'home' },
        { id: 9, away: 'Browns', home: 'Raiders', spread: 3.5, favorite: 'home' },
        { id: 10, away: 'Jaguars', home: 'Cardinals', spread: 2.5, favorite: 'away' },
        { id: 11, away: 'Falcons', home: 'Saints', spread: 1.5, favorite: 'home' },
        { id: 12, away: 'Eagles', home: 'Cowboys', spread: 3, favorite: 'away' },
        { id: 13, away: 'Buccs', home: 'Rams', spread: 7, favorite: 'home' },
        { id: 14, away: 'Panthers', home: '49ers', spread: 7.5, favorite: 'home' }
    ],
    13: [
        { id: 1, away: 'Packers', home: 'Lions', spread: 2.5, favorite: 'home' },
        { id: 2, away: 'Chiefs', home: 'Cowboys', spread: 3.5, favorite: 'away' },
        { id: 3, away: 'Bengals', home: 'Ravens', spread: 7, favorite: 'home' },
        { id: 4, away: 'Bears', home: 'Eagles', spread: 7, favorite: 'home' },
        { id: 5, away: 'Cardinals', home: 'Buccs', spread: 2.5, favorite: 'home' },
        { id: 6, away: 'Falcons', home: 'Jets', spread: 2.5, favorite: 'away' },
        { id: 7, away: 'Texans', home: 'Colts', spread: 4.5, favorite: 'home' },
        { id: 8, away: 'Jaguars', home: 'Titans', spread: 6.5, favorite: 'away' },
        { id: 9, away: 'Rams', home: 'Panthers', spread: 10.5, favorite: 'away' },
        { id: 10, away: 'Saints', home: 'Dolphins', spread: 5.5, favorite: 'home' },
        { id: 11, away: '49ers', home: 'Browns', spread: 5.5, favorite: 'away' },
        { id: 12, away: 'Vikings', home: 'Seahawks', spread: 11.5, favorite: 'home' },
        { id: 13, away: 'Bills', home: 'Steelers', spread: 3.5, favorite: 'away' },
        { id: 14, away: 'Raiders', home: 'Chargers', spread: 9.5, favorite: 'home' },
        { id: 15, away: 'Broncos', home: 'Commanders', spread: 5.5, favorite: 'away' },
        { id: 16, away: 'Giants', home: 'Patriots', spread: 7.5, favorite: 'home' }
    ],
    14: [
        { id: 1, away: 'Cowboys', home: 'Lions', spread: 3.5, favorite: 'home' },
        { id: 2, away: 'Bengals', home: 'Bills', spread: 5.5, favorite: 'home' },
        { id: 3, away: 'Colts', home: 'Jaguars', spread: 1.5, favorite: 'away' },
        { id: 4, away: 'Dolphins', home: 'Jets', spread: 3, favorite: 'away' },
        { id: 5, away: 'Saints', home: 'Buccs', spread: 8.5, favorite: 'home' },
        { id: 6, away: 'Steelers', home: 'Ravens', spread: 5.5, favorite: 'home' },
        { id: 7, away: 'Seahawks', home: 'Falcons', spread: 6.5, favorite: 'away' },
        { id: 8, away: 'Titans', home: 'Browns', spread: 3.5, favorite: 'home' },
        { id: 9, away: 'Commanders', home: 'Vikings', spread: 1.5, favorite: 'home' },
        { id: 10, away: 'Broncos', home: 'Raiders', spread: 7.5, favorite: 'away' },
        { id: 11, away: 'Bears', home: 'Packers', spread: 6.5, favorite: 'home' },
        { id: 12, away: 'Rams', home: 'Cardinals', spread: 9.5, favorite: 'away' },
        { id: 13, away: 'Texans', home: 'Chiefs', spread: 3.5, favorite: 'home' },
        { id: 14, away: 'Eagles', home: 'Chargers', spread: 2.5, favorite: 'away' }
    ],
    15: [
        { id: 1, away: 'Falcons', home: 'Buccs', spread: 5.5, favorite: 'home' },
        { id: 2, away: 'Cardinals', home: 'Texans', spread: 10.5, favorite: 'home' },
        { id: 3, away: 'Ravens', home: 'Bengals', spread: 2.5, favorite: 'away' },
        { id: 4, away: 'Bills', home: 'Patriots', spread: 1.5, favorite: 'away' },
        { id: 5, away: 'Browns', home: 'Bears', spread: 7.5, favorite: 'home' },
        { id: 6, away: 'Raiders', home: 'Eagles', spread: 11.5, favorite: 'home' },
        { id: 7, away: 'Chargers', home: 'Chiefs', spread: 5.5, favorite: 'home' },
        { id: 8, away: 'Jets', home: 'Jaguars', spread: 13.5, favorite: 'home' },
        { id: 9, away: 'Commanders', home: 'Giants', spread: 2.5, favorite: 'home' },
        { id: 10, away: 'Panthers', home: 'Saints', spread: 2.5, favorite: 'away' },
        { id: 11, away: 'Lions', home: 'Rams', spread: 5.5, favorite: 'home' },
        { id: 12, away: 'Packers', home: 'Broncos', spread: 1.5, favorite: 'away' },
        { id: 13, away: 'Colts', home: 'Seahawks', spread: 13.5, favorite: 'home' },
        { id: 14, away: 'Titans', home: '49ers', spread: 12.5, favorite: 'home' },
        { id: 15, away: 'Vikings', home: 'Cowboys', spread: 5.5, favorite: 'home' },
        { id: 16, away: 'Dolphins', home: 'Steelers', spread: 3, favorite: 'home' }
    ]
};

const HISTORICAL_RESULTS = {
    1: {
        1: { awayScore: 20, homeScore: 24, winner: 'home' },
        2: { awayScore: 21, homeScore: 27, winner: 'home' },
        3: { awayScore: 20, homeScore: 13, winner: 'away' },
        4: { awayScore: 10, homeScore: 26, winner: 'home' },
        5: { awayScore: 17, homeScore: 16, winner: 'away' },
        6: { awayScore: 20, homeScore: 13, winner: 'away' },
        7: { awayScore: 8, homeScore: 33, winner: 'home' },
        8: { awayScore: 6, homeScore: 21, winner: 'home' },
        9: { awayScore: 34, homeScore: 32, winner: 'away' },
        10: { awayScore: 23, homeScore: 20, winner: 'away' },
        11: { awayScore: 17, homeScore: 13, winner: 'away' },
        12: { awayScore: 12, homeScore: 20, winner: 'home' },
        13: { awayScore: 13, homeScore: 27, winner: 'home' },
        14: { awayScore: 9, homeScore: 13, winner: 'home' },
        15: { awayScore: 40, homeScore: 41, winner: 'home' },
        16: { awayScore: 27, homeScore: 24, winner: 'away' }
    },
    2: {
        1: { awayScore: 18, homeScore: 27, winner: 'home' },
        2: { awayScore: 30, homeScore: 10, winner: 'away' },
        3: { awayScore: 21, homeScore: 52, winner: 'home' },
        4: { awayScore: 17, homeScore: 41, winner: 'home' },
        5: { awayScore: 27, homeScore: 31, winner: 'home' },
        6: { awayScore: 33, homeScore: 19, winner: 'away' },
        7: { awayScore: 33, homeScore: 27, winner: 'away' },
        8: { awayScore: 37, homeScore: 40, winner: 'home' },
        9: { awayScore: 26, homeScore: 21, winner: 'away' },
        10: { awayScore: 31, homeScore: 17, winner: 'away' },
        11: { awayScore: 22, homeScore: 27, winner: 'home' },
        12: { awayScore: 28, homeScore: 29, winner: 'home' },
        13: { awayScore: 20, homeScore: 17, winner: 'away' },
        14: { awayScore: 22, homeScore: 6, winner: 'away' },
        15: { awayScore: 20, homeScore: 19, winner: 'away' },
        16: { awayScore: 20, homeScore: 9, winner: 'away' }
    },
    3: {
        1: { awayScore: 21, homeScore: 31, winner: 'home' },
        2: { awayScore: 0, homeScore: 30, winner: 'home' },
        3: { awayScore: 10, homeScore: 48, winner: 'home' },
        4: { awayScore: 10, homeScore: 13, winner: 'home' },
        5: { awayScore: 10, homeScore: 17, winner: 'home' },
        6: { awayScore: 41, homeScore: 20, winner: 'away' },
        7: { awayScore: 24, homeScore: 41, winner: 'home' },
        8: { awayScore: 26, homeScore: 33, winner: 'home' },
        9: { awayScore: 27, homeScore: 29, winner: 'home' },
        10: { awayScore: 21, homeScore: 14, winner: 'away' },
        11: { awayScore: 20, homeScore: 23, winner: 'home' },
        12: { awayScore: 13, homeScore: 44, winner: 'home' },
        13: { awayScore: 15, homeScore: 16, winner: 'home' },
        14: { awayScore: 14, homeScore: 31, winner: 'home' },
        15: { awayScore: 22, homeScore: 9, winner: 'away' },
        16: { awayScore: 38, homeScore: 30, winner: 'away' }
    },
    4: {
        1: { awayScore: 23, homeScore: 20, winner: 'away' },
        2: { awayScore: 20, homeScore: 23, winner: 'home' },
        3: { awayScore: 13, homeScore: 42, winner: 'home' },
        4: { awayScore: 10, homeScore: 34, winner: 'home' },
        5: { awayScore: 18, homeScore: 21, winner: 'home' },
        6: { awayScore: 19, homeScore: 31, winner: 'home' },
        7: { awayScore: 31, homeScore: 25, winner: 'away' },
        8: { awayScore: 0, homeScore: 26, winner: 'home' },
        9: { awayScore: 27, homeScore: 34, winner: 'home' },
        10: { awayScore: 20, homeScore: 27, winner: 'home' },
        11: { awayScore: 26, homeScore: 21, winner: 'away' },
        12: { awayScore: 20, homeScore: 37, winner: 'home' },
        13: { awayScore: 25, homeScore: 24, winner: 'away' },
        14: { awayScore: 40, homeScore: 40, winner: 'away' },
        15: { awayScore: 21, homeScore: 27, winner: 'home' },
        16: { awayScore: 3, homeScore: 28, winner: 'home' }
    },
    5: {
        1: { awayScore: 26, homeScore: 23, winner: 'away' },
        2: { awayScore: 21, homeScore: 17, winner: 'away' },
        3: { awayScore: 37, homeScore: 22, winner: 'away' },
        4: { awayScore: 21, homeScore: 17, winner: 'away' },
        5: { awayScore: 44, homeScore: 10, winner: 'away' },
        6: { awayScore: 6, homeScore: 40, winner: 'home' },
        7: { awayScore: 24, homeScore: 27, winner: 'home' },
        8: { awayScore: 14, homeScore: 26, winner: 'home' },
        9: { awayScore: 38, homeScore: 35, winner: 'away' },
        10: { awayScore: 22, homeScore: 21, winner: 'away' },
        11: { awayScore: 37, homeScore: 24, winner: 'away' },
        12: { awayScore: 27, homeScore: 10, winner: 'away' },
        13: { awayScore: 23, homeScore: 20, winner: 'away' },
        14: { awayScore: 28, homeScore: 31, winner: 'home' }
    },
    6: {
        1: { awayScore: 17, homeScore: 34, winner: 'home' },
        2: { awayScore: 13, homeScore: 11, winner: 'away' },
        3: { awayScore: 27, homeScore: 31, winner: 'home' },
        4: { awayScore: 9, homeScore: 23, winner: 'home' },
        5: { awayScore: 27, homeScore: 30, winner: 'home' },
        6: { awayScore: 29, homeScore: 27, winner: 'away' },
        7: { awayScore: 17, homeScore: 3, winner: 'away' },
        8: { awayScore: 25, homeScore: 19, winner: 'away' },
        9: { awayScore: 20, homeScore: 12, winner: 'away' },
        10: { awayScore: 10, homeScore: 20, winner: 'home' },
        11: { awayScore: 18, homeScore: 27, winner: 'home' },
        12: { awayScore: 19, homeScore: 30, winner: 'home' },
        13: { awayScore: 17, homeScore: 30, winner: 'home' },
        14: { awayScore: 14, homeScore: 24, winner: 'home' },
        15: { awayScore: 25, homeScore: 24, winner: 'away' }
    },
    7: {
        1: { awayScore: 31, homeScore: 33, winner: 'home' },
        2: { awayScore: 35, homeScore: 7, winner: 'away' },
        3: { awayScore: 13, homeScore: 6, winner: 'away' },
        4: { awayScore: 0, homeScore: 31, winner: 'home' },
        5: { awayScore: 6, homeScore: 31, winner: 'home' },
        6: { awayScore: 31, homeScore: 13, winner: 'away' },
        7: { awayScore: 14, homeScore: 26, winner: 'home' },
        8: { awayScore: 28, homeScore: 22, winner: 'away' },
        9: { awayScore: 38, homeScore: 24, winner: 'away' },
        10: { awayScore: 32, homeScore: 33, winner: 'home' },
        11: { awayScore: 27, homeScore: 23, winner: 'away' },
        12: { awayScore: 22, homeScore: 44, winner: 'home' },
        13: { awayScore: 10, homeScore: 20, winner: 'home' },
        14: { awayScore: 9, homeScore: 24, winner: 'home' },
        15: { awayScore: 19, homeScore: 27, winner: 'home' }
    },
    8: {
        1: { awayScore: 10, homeScore: 37, winner: 'home' },
        2: { awayScore: 40, homeScore: 9, winner: 'away' },
        3: { awayScore: 16, homeScore: 30, winner: 'home' },
        4: { awayScore: 13, homeScore: 32, winner: 'home' },
        5: { awayScore: 34, homeScore: 10, winner: 'away' },
        6: { awayScore: 20, homeScore: 38, winner: 'home' },
        7: { awayScore: 39, homeScore: 38, winner: 'away' },
        8: { awayScore: 15, homeScore: 26, winner: 'home' },
        9: { awayScore: 23, homeScore: 3, winner: 'away' },
        10: { awayScore: 24, homeScore: 44, winner: 'home' },
        11: { awayScore: 14, homeScore: 38, winner: 'home' },
        12: { awayScore: 35, homeScore: 25, winner: 'away' },
        13: { awayScore: 7, homeScore: 28, winner: 'home' }
    },
    9: {
        1: { awayScore: 28, homeScore: 6, winner: 'away' },
        2: { awayScore: 23, homeScore: 24, winner: 'home' },
        3: { awayScore: 16, homeScore: 13, winner: 'away' },
        4: { awayScore: 47, homeScore: 42, winner: 'away' },
        5: { awayScore: 18, homeScore: 15, winner: 'away' },
        6: { awayScore: 20, homeScore: 27, winner: 'home' },
        7: { awayScore: 27, homeScore: 20, winner: 'away' },
        8: { awayScore: 27, homeScore: 24, winner: 'away' },
        9: { awayScore: 34, homeScore: 24, winner: 'away' },
        10: { awayScore: 30, homeScore: 29, winner: 'away' },
        11: { awayScore: 10, homeScore: 34, winner: 'home' },
        12: { awayScore: 21, homeScore: 28, winner: 'home' },
        13: { awayScore: 38, homeScore: 14, winner: 'away' },
        14: { awayScore: 27, homeScore: 17, winner: 'away' }
    },
    10: {
        1: { awayScore: 7, homeScore: 10, winner: 'home' },
        2: { awayScore: 25, homeScore: 31, winner: 'home' },
        3: { awayScore: 27, homeScore: 19, winner: 'away' },
        4: { awayScore: 13, homeScore: 30, winner: 'home' },
        5: { awayScore: 20, homeScore: 27, winner: 'home' },
        6: { awayScore: 29, homeScore: 36, winner: 'home' },
        7: { awayScore: 28, homeScore: 23, winner: 'away' },
        8: { awayScore: 17, homeScore: 7, winner: 'away' },
        9: { awayScore: 20, homeScore: 24, winner: 'home' },
        10: { awayScore: 22, homeScore: 44, winner: 'home' },
        11: { awayScore: 44, homeScore: 22, winner: 'away' },
        12: { awayScore: 42, homeScore: 26, winner: 'away' },
        13: { awayScore: 10, homeScore: 25, winner: 'home' },
        14: { awayScore: 10, homeScore: 7, winner: 'away' }
    },
    11: {
        1: { awayScore: 14, homeScore: 27, winner: 'home' },
        2: { awayScore: 13, homeScore: 16, winner: 'home' },
        3: { awayScore: 30, homeScore: 27, winner: 'away' },
        4: { awayScore: 19, homeScore: 17, winner: 'away' },
        5: { awayScore: 12, homeScore: 34, winner: 'home' },
        6: { awayScore: 27, homeScore: 20, winner: 'away' },
        7: { awayScore: 16, homeScore: 13, winner: 'away' },
        8: { awayScore: 6, homeScore: 35, winner: 'home' },
        9: { awayScore: 32, homeScore: 44, winner: 'home' },
        10: { awayScore: 41, homeScore: 22, winner: 'away' },
        11: { awayScore: 19, homeScore: 21, winner: 'home' },
        12: { awayScore: 23, homeScore: 16, winner: 'away' },
        13: { awayScore: 19, homeScore: 22, winner: 'home' },
        14: { awayScore: 9, homeScore: 16, winner: 'home' },
        15: { awayScore: 33, homeScore: 16, winner: 'away' }
    },
    12: {
        1: { awayScore: 19, homeScore: 23, winner: 'home' },
        2: { awayScore: 6, homeScore: 23, winner: 'home' },
        3: { awayScore: 26, homeScore: 20, winner: 'away' },
        4: { awayScore: 27, homeScore: 34, winner: 'home' },
        5: { awayScore: 10, homeScore: 23, winner: 'home' },
        6: { awayScore: 28, homeScore: 31, winner: 'home' },
        7: { awayScore: 30, homeScore: 24, winner: 'away' },
        8: { awayScore: 20, homeScore: 23, winner: 'home' },
        9: { awayScore: 24, homeScore: 10, winner: 'away' },
        10: { awayScore: 27, homeScore: 24, winner: 'away' },
        11: { awayScore: 24, homeScore: 10, winner: 'away' },
        12: { awayScore: 21, homeScore: 24, winner: 'home' },
        13: { awayScore: 7, homeScore: 34, winner: 'home' },
        14: { awayScore: 9, homeScore: 20, winner: 'home' }
    },
    13: {
        1: { awayScore: 31, homeScore: 24, winner: 'away' },
        2: { awayScore: 28, homeScore: 31, winner: 'home' },
        3: { awayScore: 32, homeScore: 14, winner: 'away' },
        4: { awayScore: 24, homeScore: 15, winner: 'away' },
        5: { awayScore: 17, homeScore: 20, winner: 'home' },
        6: { awayScore: 24, homeScore: 27, winner: 'home' },
        7: { awayScore: 20, homeScore: 16, winner: 'away' },
        8: { awayScore: 25, homeScore: 3, winner: 'away' },
        9: { awayScore: 28, homeScore: 31, winner: 'home' },
        10: { awayScore: 17, homeScore: 21, winner: 'home' },
        11: { awayScore: 26, homeScore: 8, winner: 'away' },
        12: { awayScore: 0, homeScore: 26, winner: 'home' },
        13: { awayScore: 26, homeScore: 7, winner: 'away' },
        14: { awayScore: 14, homeScore: 31, winner: 'home' },
        15: { awayScore: 27, homeScore: 26, winner: 'away' },
        16: { awayScore: 15, homeScore: 33, winner: 'home' }
    },
    14: {
        1: { awayScore: 30, homeScore: 44, winner: 'home' },
        2: { awayScore: 34, homeScore: 39, winner: 'home' },
        3: { awayScore: 19, homeScore: 39, winner: 'home' },
        4: { awayScore: 34, homeScore: 10, winner: 'away' },
        5: { awayScore: 24, homeScore: 20, winner: 'away' },
        6: { awayScore: 27, homeScore: 22, winner: 'away' },
        7: { awayScore: 37, homeScore: 9, winner: 'away' },
        8: { awayScore: 31, homeScore: 29, winner: 'away' },
        9: { awayScore: 0, homeScore: 31, winner: 'home' },
        10: { awayScore: 24, homeScore: 17, winner: 'away' },
        11: { awayScore: 21, homeScore: 28, winner: 'home' },
        12: { awayScore: 45, homeScore: 17, winner: 'away' },
        13: { awayScore: 20, homeScore: 10, winner: 'away' },
        14: { awayScore: 19, homeScore: 22, winner: 'home' }
    },
    15: {
        1: { awayScore: 29, homeScore: 28, winner: 'away' },
        2: { awayScore: 20, homeScore: 40, winner: 'home' },
        3: { awayScore: 24, homeScore: 0, winner: 'away' },
        4: { awayScore: 35, homeScore: 31, winner: 'away' },
        5: { awayScore: 3, homeScore: 31, winner: 'home' },
        6: { awayScore: 0, homeScore: 31, winner: 'home' },
        7: { awayScore: 16, homeScore: 13, winner: 'away' },
        8: { awayScore: 20, homeScore: 48, winner: 'home' },
        9: { awayScore: 29, homeScore: 21, winner: 'away' },
        10: { awayScore: 17, homeScore: 20, winner: 'home' },
        11: { awayScore: 34, homeScore: 41, winner: 'home' },
        12: { awayScore: 26, homeScore: 34, winner: 'home' },
        13: { awayScore: 16, homeScore: 18, winner: 'home' },
        14: { awayScore: 24, homeScore: 37, winner: 'home' },
        15: { awayScore: 34, homeScore: 26, winner: 'away' },
        16: { awayScore: 15, homeScore: 28, winner: 'home' }
    }
};

const HISTORICAL_PICKS = {
    1: {
        'Dylan': {
            1: { line: 'home', winner: 'home' },
            2: { line: 'away', winner: 'away' },
            3: { line: 'home', winner: 'away' },
            4: { line: 'home', winner: 'home' },
            5: { line: 'home', winner: 'away' },
            6: { line: 'home', winner: 'home' },
            7: { line: 'home', winner: 'home' },
            8: { line: 'home', winner: 'home' },
            9: { line: 'away', winner: 'away' },
            10: { line: 'home', winner: 'home' },
            11: { line: 'home', winner: 'home' },
            12: { line: 'home', winner: 'home' },
            13: { line: 'home', winner: 'home' },
            14: { line: 'home', winner: 'home' },
            15: { line: 'home', winner: 'home' },
            16: { line: 'away', winner: 'away' }
        },
        'Sean': {
            1: { line: 'away', winner: 'home' },
            2: { line: 'away', winner: 'away' },
            3: { line: 'away', winner: 'away' },
            4: { line: 'home', winner: 'home' },
            5: { line: 'home', winner: 'away' },
            6: { line: 'away', winner: 'away' },
            7: { line: 'away', winner: 'away' },
            8: { line: 'away', winner: 'home' },
            9: { line: 'away', winner: 'away' },
            10: { line: 'home', winner: 'home' },
            11: { line: 'away', winner: 'away' },
            12: { line: 'away', winner: 'home' },
            13: { line: 'away', winner: 'home' },
            14: { line: 'home', winner: 'home' },
            15: { line: 'away', winner: 'away' },
            16: { line: 'home', winner: 'away' }
        },
        'Daniel': {
            1: { line: 'home', winner: 'home' },
            2: { line: 'home', winner: 'home' },
            3: { line: 'home', winner: 'away' },
            4: { line: 'home', winner: 'home' },
            5: { line: 'away', winner: 'away' },
            6: { line: 'home', winner: 'home' },
            7: { line: 'away', winner: 'away' },
            8: { line: 'home', winner: 'home' },
            9: { line: 'away', winner: 'away' },
            10: { line: 'away', winner: 'away' },
            11: { line: 'away', winner: 'away' },
            12: { line: 'home', winner: 'home' },
            13: { line: 'away', winner: 'away' },
            14: { line: 'away', winner: 'away' },
            15: { line: 'away', winner: 'away' },
            16: { line: 'away', winner: 'away' }
        },
        'Jason': {
            1: { line: 'away', winner: 'home' },
            2: { line: 'home', winner: 'home' },
            3: { line: 'away', winner: 'away' },
            4: { line: 'home', winner: 'home' },
            5: { line: 'away', winner: 'away' },
            6: { line: 'home', winner: 'home' },
            7: { line: 'away', winner: 'away' },
            8: { line: 'away', winner: 'home' },
            9: { line: 'home', winner: 'away' },
            10: { line: 'home', winner: 'home' },
            11: { line: 'home', winner: 'home' },
            12: { line: 'home', winner: 'home' },
            13: { line: 'away', winner: 'away' },
            14: { line: 'away', winner: 'away' },
            15: { line: 'home', winner: 'home' },
            16: { line: 'away', winner: 'away' }
        },
        'Stephen': {
            1: { line: 'away', winner: 'home' },
            2: { line: 'home', winner: 'home' },
            3: { line: 'home', winner: 'away' },
            4: { line: 'home', winner: 'home' },
            5: { line: 'away', winner: 'away' },
            6: { line: 'home', winner: 'home' },
            7: { line: 'away', winner: 'away' },
            8: { line: 'away', winner: 'home' },
            9: { line: 'away', winner: 'away' },
            10: { line: 'away', winner: 'away' },
            11: { line: 'away', winner: 'away' },
            12: { line: 'away', winner: 'home' },
            13: { line: 'away', winner: 'away' },
            14: { line: 'away', winner: 'away' },
            15: { line: 'home', winner: 'home' },
            16: { line: 'home', winner: 'away' }
        }
    },
    2: {
        'Dylan': {
            1: { line: 'away', winner: 'home' },
            2: { line: 'home', winner: 'away' },
            3: { line: 'home', winner: 'home' },
            4: { line: 'away', winner: 'home' },
            5: { line: 'home', winner: 'home' },
            6: { line: 'away', winner: 'away' },
            7: { line: 'away', winner: 'away' },
            8: { line: 'home', winner: 'home' },
            9: { line: 'away', winner: 'away' },
            10: { line: 'away', winner: 'away' },
            11: { line: 'home', winner: 'away' },
            12: { line: 'home', winner: 'home' },
            13: { line: 'away', winner: 'away' },
            14: { line: 'home', winner: 'away' },
            15: { line: 'away', winner: 'away' },
            16: { line: 'away', winner: 'away' }
        },
        'Sean': {
            1: { line: 'home', winner: 'home' },
            2: { line: 'home', winner: 'away' },
            3: { line: 'away', winner: 'home' },
            4: { line: 'away', winner: 'home' },
            5: { line: 'away', winner: 'away' },
            6: { line: 'home', winner: 'away' },
            7: { line: 'home', winner: 'away' },
            8: { line: 'away', winner: 'home' },
            9: { line: 'away', winner: 'away' },
            10: { line: 'away', winner: 'away' },
            11: { line: 'away', winner: 'away' },
            12: { line: 'home', winner: 'home' },
            13: { line: 'home', winner: 'away' },
            14: { line: 'home', winner: 'away' },
            15: { line: 'home', winner: 'away' },
            16: { line: 'away', winner: 'away' }
        },
        'Daniel': {
            1: { line: 'home', winner: 'home' },
            2: { line: 'away', winner: 'away' },
            3: { line: 'home', winner: 'home' },
            4: { line: 'away', winner: 'home' },
            5: { line: 'home', winner: 'home' },
            6: { line: 'away', winner: 'away' },
            7: { line: 'home', winner: 'away' },
            8: { line: 'home', winner: 'home' },
            9: { line: 'away', winner: 'away' },
            10: { line: 'away', winner: 'away' },
            11: { line: 'away', winner: 'away' },
            12: { line: 'away', winner: 'away' },
            13: { line: 'away', winner: 'away' },
            14: { line: 'home', winner: 'away' },
            15: { line: 'home', winner: 'away' },
            16: { line: 'away', winner: 'away' }
        },
        'Jason': {
            1: { line: 'away', winner: 'home' },
            2: { line: 'away', winner: 'away' },
            3: { line: 'away', winner: 'home' },
            4: { line: 'away', winner: 'home' },
            5: { line: 'away', winner: 'away' },
            6: { line: 'away', winner: 'away' },
            7: { line: 'away', winner: 'away' },
            8: { line: 'home', winner: 'home' },
            9: { line: 'home', winner: 'away' },
            10: { line: 'away', winner: 'away' },
            11: { line: 'home', winner: 'away' },
            12: { line: 'home', winner: 'home' },
            13: { line: 'away', winner: 'away' },
            14: { line: 'away', winner: 'away' },
            15: { line: 'home', winner: 'away' },
            16: { line: 'away', winner: 'away' }
        },
        'Stephen': {
            1: { line: 'away', winner: 'away' },
            2: { line: 'home', winner: 'away' },
            3: { line: 'away', winner: 'home' },
            4: { line: 'home', winner: 'home' },
            5: { line: 'home', winner: 'home' },
            6: { line: 'home', winner: 'away' },
            7: { line: 'away', winner: 'away' },
            8: { line: 'home', winner: 'home' },
            9: { line: 'away', winner: 'away' },
            10: { line: 'away', winner: 'away' },
            11: { line: 'away', winner: 'away' },
            12: { line: 'home', winner: 'home' },
            13: { line: 'away', winner: 'away' },
            14: { line: 'home', winner: 'away' },
            15: { line: 'away', winner: 'away' },
            16: { line: 'away', winner: 'away' }
        }
    }
};

// Function to load historical data into the app
function loadHistoricalData() {
    // Merge HISTORICAL_GAMES into NFL_GAMES_BY_WEEK
    for (const week in HISTORICAL_GAMES) {
        if (!NFL_GAMES_BY_WEEK[week] || NFL_GAMES_BY_WEEK[week].length === 0) {
            NFL_GAMES_BY_WEEK[week] = HISTORICAL_GAMES[week];
        }
    }

    // Merge HISTORICAL_RESULTS into NFL_RESULTS_BY_WEEK
    for (const week in HISTORICAL_RESULTS) {
        if (!NFL_RESULTS_BY_WEEK[week]) {
            NFL_RESULTS_BY_WEEK[week] = HISTORICAL_RESULTS[week];
        }
    }

    // Merge HISTORICAL_PICKS into allPicks
    for (const week in HISTORICAL_PICKS) {
        if (!allPicks[week]) {
            allPicks[week] = HISTORICAL_PICKS[week];
        }
    }

    console.log('Historical data loaded for weeks 1-15');
}

// This will be called from app.js init() function
